### ISSUE TITLE
OpenMP compile error: mono_picture_asset

### ISSUE THREAD

**Issue by tschiemer** [cth103/libdcp#1]
```
../src/mono_picture_asset.cc:131:2: error: statement after '#pragma omp parallel for' must be a for loop
        shared_ptr<MonoPictureAssetReader> reader = start_read ();
        ^
../src/mono_picture_asset.cc:141:49: error: use of undeclared identifier 'reader'
                        shared_ptr<const MonoPictureFrame> frame_A = reader->get_frame (i);
                                                                     ^
2 errors generated.
```

https://github.com/cth103/libdcp/blob/9a0c89b3e2ddf56af5433ab96ff8809c05a8b9a4/src/mono_picture_asset.cc#L128

Moving  lines 131-132 

```
	shared_ptr<MonoPictureAssetReader> reader = start_read ();
	shared_ptr<MonoPictureAssetReader> other_reader = other_picture->start_read ();
```
before the openmp statement makes it compile - but I'm not familiar with openmp, so I don't know if that would break something (but openmp wouldn't work anyways, as it doesn't compile?)

**Comment by cth103** [comment]
Thanks, I applied your suggested fix as e639e3597db2ef2cf0f51e2fcc62725d579927bd so let's see if that's any better.
