### ISSUE TITLE
Help with decoding a single frame

### ISSUE THREAD

**Issue by perryflynn** [cth103/libdcp#11]
Hi,

I reverse engineer the DCI Encryption right now, just for fun and educational purposes. 

I've created a small encrypted DCP with DCP-o-Matic (thank you for that great tool btw). I was able to extract and decrypt the first encrypted frame.

Hexdump:

```
00000000  3a f0 b7 f5 53 49 eb b7  c0 c0 cb a5 c9 2f 35 19  |:...SI......./5.|
00000010  00 00 00 00 00 00 00 00  00 00 07 ce 00 00 04 38  |...............8|
00000020  00 00 00 00 00 00 00 00  00 03 0b 01 01 0b 01 01  |................|
00000030  0b 01 01 ff 52 00 12 01  04 00 01 01 05 03 03 00  |....R...........|
00000040  00 77 88 88 88 88 88 ff  5c 00 23 22 97 20 96 f0  |.w......\.#". ..|
00000050  96 f0 96 c0 8f 00 8f 00  8e e0 87 50 87 50 87 68  |...........P.P.h|
00000060  70 05 70 05 70 47 77 d3  77 d3 77 62 ff 55 00 13  |p.p.pGw.w.wb.U..|
00000070  00 50 00 00 00 4d 40 00  00 00 00 49 00 00 00 00  |.P...M@....I....|
00000080  49 ff 64 00 0a 00 01 6c  69 62 64 63 70 ff 90 00  |I.d....libdcp...|
00000090  0a 00 00 00 00 4d 40 00  03 ff 93 ef fe 2c 71 ff  |.....M@......,q.|
```

Now I would like to export the frame as JPEG2000 / jpg image.

Is this easy possible or do I mix things here? Could you give me a hint where I can find the decoding logic for a single frame in libdcp?

Thank you
Christian

**Comment by cth103** [comment]
Hi, I'm not quite clear what you are trying to do - do you want to extract a frame from the MXF, or decode JPEG2000 to a bitmap (or something else?)

[`decompress_j2k`](https://github.com/cth103/libdcp/blob/c9b3af92c43cb649137c88eaa48802197a4bbb06/src/j2k_transcode.cc#L126) will take JPEG2000 data and give you a bitmap.

To extract frames from MXF you can create a `MonoPictureAsset` and then call `start_read()` to get a `MonoPictureAssetReader` which will then give you frames.

**Comment by perryflynn** [comment]
Hi, correct, I would like to export the frame as a bitmap. Just as a proof, that I did everything correct.

I used MXFInspect to get the offset and length of one encrypted frame and then used `dd`, `hexdump` and `openssl` to do the parsing manually.

Now I would like to pass the binary file (see hexdump) which came out of `openssl enc -aes128 -d` into `somefunction()` and the function should return a bitmap image which can be viewed on a PC.

Will take a look into your code and try to reimplement that in bash or python. (Again just for fun and to understand it better)

**Comment by cth103** [comment]
OK it sounds like you first need to do what's in `dcp::decompress_j2k()` (which basically just calls libopenjpeg) and then take that bitmap and save it as PNG or TIFF. You also need a colourspace conversion if you want the colours to look correct.

**Comment by perryflynn** [comment]
Great, thank you.

I found an easier solution. I sliced a frame from an unencrypted movie (file named `image.j2k`) and was able to just open it in Gimp. Which confused me. It is not possible with the decrypted frame.

When comparing the hexdumps, just the first 16 bytes of the beginning of the files are different:

Previously encrypted frame after decrypting it (cannot be opened in Gimp):

```
00000000  08 fc 3e 61 d8 7f 78 e7  da 58 63 7b d2 25 93 5a  |..>a..x..Xc{.%.Z|
00000010  00 00 00 00 00 00 00 00  00 00 07 ce 00 00 04 38  |...............8|
00000020  00 00 00 00 00 00 00 00  00 03 0b 01 01 0b 01 01  |................|
00000030  0b 01 01 ff 52 00 12 01  04 00 01 01 05 03 03 00  |....R...........|
00000040  00 77 88 88 88 88 88 ff  5c 00 23 22 97 20 96 f0  |.w......\.#". ..|
00000050  96 f0 96 c0 8f 00 8f 00  8e e0 87 50 87 50 87 68  |...........P.P.h|
00000060  70 05 70 05 70 47 77 d3  77 d3 77 62 ff 55 00 13  |p.p.pGw.w.wb.U..|
00000070  00 50 00 00 06 c6 d0 00  00 03 35 be 00 00 01 ee  |.P........5.....|
00000080  85 ff 64 00 0a 00 01 6c  69 62 64 63 70 ff 90 00  |..d....libdcp...|
00000090  0a 00 00 00 06 c6 d0 00  03 ff 93 e7 ff 05 ed a1  |................|
```

Unencrypted frame, just sliced from mxf (can be opened in Gimp):

```
00000000  ff 4f ff 51 00 2f 00 03  00 00 07 ce 00 00 04 38  |.O.Q./.........8|
00000010  00 00 00 00 00 00 00 00  00 00 07 ce 00 00 04 38  |...............8|
00000020  00 00 00 00 00 00 00 00  00 03 0b 01 01 0b 01 01  |................|
00000030  0b 01 01 ff 52 00 12 01  04 00 01 01 05 03 03 00  |....R...........|
00000040  00 77 88 88 88 88 88 ff  5c 00 23 22 97 20 96 f0  |.w......\.#". ..|
00000050  96 f0 96 c0 8f 00 8f 00  8e e0 87 50 87 50 87 68  |...........P.P.h|
00000060  70 05 70 05 70 47 77 d3  77 d3 77 62 ff 55 00 13  |p.p.pGw.w.wb.U..|
00000070  00 50 00 00 06 c6 d0 00  00 03 35 be 00 00 01 ee  |.P........5.....|
00000080  85 ff 64 00 0a 00 01 6c  69 62 64 63 70 ff 90 00  |..d....libdcp...|
00000090  0a 00 00 00 06 c6 d0 00  03 ff 93 e7 ff 05 ed a1  |................|
```

I just took the first 16 bytes of the unencrypted frame and replaced with that the first 16 bytes of the decrypted frame and I am able to open it in Gimp. 🎉 

Color looks a little bit off but that's enough to prove, that I did it right. 

[Wikipedia says](https://en.wikipedia.org/wiki/List_of_file_signatures), that `FF 4F FF 51` is another magic string for j2k files. No clue what the original 16 bytes mean.

Do you have an idea why the first 16 bytes are "wrong"/different? Since the rest of the data is exactly identical, I don't think that I did a mistake while decrypting/slicing it.

**Comment by cth103** [comment]
Nothing springs to mind, to be honest. FF 4F is the "start of codestream" marker so if it's not there I'm not surprised the file can't be opened.
