### ISSUE TITLE
OSX (mojave) boost too old -> clang: error: unsupported option '-fopenmp'

### ISSUE THREAD

**Issue by tschiemer** [cth103/libdcp#3]
Apple's clang compiler does not support openmp out of the box, so trying to `waf configure --enable-openmp` will fail at the first compiler test checking the boost version and thus giving a misleading error message `Please install boost version 1.45 or higher.` (introducing a seperate check for openmp support might be an idea)

Fails:
```
Apple LLVM version 10.0.1 (clang-1001.0.46.4)
Target: x86_64-apple-darwin18.6.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```

using the llvm compiler provided through homebrew (`brew install llvm`) would resolve the issue, but requires making sure the waf script selects the correct binary and has the right includes etc. This can be done according to what homebrew states (`brew info llvm`):

```
To use the bundled libc++ please add the following LDFLAGS:
  LDFLAGS="-L/usr/local/opt/llvm/lib -Wl,-rpath,/usr/local/opt/llvm/lib"

llvm is keg-only, which means it was not symlinked into /usr/local,
because macOS already provides this software and installing another version in
parallel can cause all kinds of trouble.

If you need to have llvm first in your PATH run:
  echo 'export PATH="/usr/local/opt/llvm/bin:$PATH"' >> ~/.bash_profile

For compilers to find llvm you may need to set:
  export LDFLAGS="-L/usr/local/opt/llvm/lib"
  export CPPFLAGS="-I/usr/local/opt/llvm/include"
```

The linker and compiler flags would have to be added to the configuration script. 

Also the rather basic includes would have to be accessible by adding the headers and include path:

`open /Library/Developer/CommandLineTools/Packages/macOS_SDK_headers_for_macOS_10.14.pkg` (once the command line tools/xcode are installed)

As explained in: https://stackoverflow.com/a/48746939/1982142

**Comment by cth103** [comment]
e7647175268369b28e96d061dfcd4a3c2a39944d adds a check that -fopenmp works: thanks!

I'm not sure that it's the wscript's job to pick an brew-installed llvm over the local clang, or any similar jobs.  I guess we could add a --brew option (or some similar special case) to the wscript...  any thoughts?

**Comment by cth103** [comment]
I think the environment variable approach is best, otherwise the wscript is liable to explode with specific settings for particular setups.

**Comment by cth103** [comment]
Any more patches to the readme are welcome :)
