### ISSUE TITLE
Compile fails on Arch Linux g++-12, libc 2.36-6

### ISSUE THREAD

**Issue by cfenell** [cth103/libdcp#8]
Hi, I am a new user trying to convert DVDs to DCP.
My fastest computers run Arch / Manjaro (g++-12, libc 2.36-6) and libdcp fails to build.
The issues I have encountered so far are
1.  j2k_transcode.cc needs a patch which is included in the AUR build. See attachment.
[0001-fix-compile-with-openjp25.patch.txt](https://github.com/cth103/libdcp/files/10149244/0001-fix-compile-with-openjp25.patch.txt)

2. smpte_subtitle_asset.cc:112:83 This gives an ambiguous overload error. I am not too familiar with C++ so don't really know where to start looking. Possibly this is a gcc-12 feature? The option --force-cpp11 is not available in the newest commit.

**Comment by cth103** [comment]
The ambiguous overloads should be fixed in 32360aedc97a0cc9acc1b1c10d2e8351dcacb549

**Comment by cth103** [comment]
I'll look at fixing j2k_transcode.cc to compile with this newer libopenjpeg

**Comment by cth103** [comment]
You shouldn't need the patch from AUR any more in 2c6d80c295dd3d10c1c9c08dd31758dd1abdf5da

**Comment by cth103** [comment]
Let me know if you still have problems!

**Comment by cfenell** [comment]
Thanks for your quick response! I am travelling this week and will check later.

**Comment by cfenell** [comment]
Thanks, dcpomatic now compiles on Arch!

I have seen a few crashes- will let you know if it happens again. So far I have encoded two DVD movies and a 4K video from my own camera.
